-- database setup
DROP DATABASE IF EXISTS RESTAURANT_APP;
CREATE DATABASE RESTAURANT_APP CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci';
USE RESTAURANT_APP;
-- independent tables
CREATE TABLE IF NOT EXISTS Client (
    id INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(10),
    username VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS Product (
    id INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    description TEXT DEFAULT 'Description not available',
    price FLOAT NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS Category (
    id INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);
-- 1..n tables
CREATE TABLE IF NOT EXISTS ProductImage (
    id INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
    productId INTEGER NOT NULL,
    path VARCHAR(200) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (productId) REFERENCES Product(id)
);
CREATE TABLE IF NOT EXISTS Orders (
    id INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
    clientId INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (clientId) REFERENCES Client(id)
);
CREATE TABLE IF NOT EXISTS Sale (
    id INTEGER NOT NULL AUTO_INCREMENT,
    orderId INTEGER NOT NULL,
    paymentMethod SMALLINT NOT NULL,
    total FLOAT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (orderId) REFERENCES Orders(id)
);
-- n..n tables
CREATE TABLE IF NOT EXISTS Category_Product (
    categoryId INTEGER NOT NULL,
    productId INTEGER NOT NULL,
    FOREIGN KEY (categoryId) REFERENCES Category(id),
    FOREIGN KEY (productId) REFERENCES Product(id)
);
CREATE TABLE IF NOT EXISTS Order_Product (
    id INTEGER NOT NULL AUTO_INCREMENT,
    orderId INTEGER NOT NULL,
    productId INTEGER NOT NULL,
    quantity SMALLINT NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    FOREIGN KEY (orderId) REFERENCES Orders(id),
    FOREIGN KEY (productId) REFERENCES Product(id)
);
