-- mysql
-- database setup
DROP DATABASE IF EXISTS RESTAURANT_APP;
CREATE DATABASE RESTAURANT_APP
CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
USE RESTAURANT_APP;
-- independent tables
CREATE TABLE IF NOT EXISTS Client (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(10),
    username VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS Product (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description TEXT NOT NULL DEFAULT 'Description not available',
    price DECIMAL(8,2) NOT NULL
);
CREATE TABLE IF NOT EXISTS Category (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);
-- 1..n tables
CREATE TABLE IF NOT EXISTS ProductImage (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    productId INTEGER NOT NULL,
    path VARCHAR(200) NOT NULL,
    FOREIGN KEY (productId) REFERENCES Product(id)
);
CREATE TABLE IF NOT EXISTS Orders (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clientId INTEGER NOT NULL,
    total DECIMAL(8,2) NOT NULL,
    confirmed BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY (clientId) REFERENCES Client(id)
);
CREATE TABLE IF NOT EXISTS Sale (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    orderId INTEGER NOT NULL,
    paymentMethod SMALLINT NOT NULL,
    FOREIGN KEY (orderId) REFERENCES Orders(id)
);
-- n..n tables
CREATE TABLE IF NOT EXISTS Category_Product (
    categoryId INTEGER NOT NULL,
    productId INTEGER NOT NULL,
    FOREIGN KEY (categoryId) REFERENCES Category(id),
    FOREIGN KEY (productId) REFERENCES Product(id)
);
CREATE TABLE IF NOT EXISTS Order_Product (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    orderId INTEGER NOT NULL,
    productId INTEGER NOT NULL,
    quantity SMALLINT NOT NULL,
    FOREIGN KEY (orderId) REFERENCES Orders(id),
    FOREIGN KEY (productId) REFERENCES Product(id)
);
